### PR TITLE
Added support for garage door toggle domain.

### PR DESCRIPTION
**Pull request by xrolfex**
This pull request is to add the toggleDomainSupport for the upcoming wink garage door components pull request.

### CODE REVIEW

**Comment by balloob** [comment]
Wouldn't it make more sense to have Wink garage doors be exposed in HA as switches? Just like the [eggminders are exposed as sensors](https://github.com/balloob/home-assistant/blob/dev/homeassistant/components/sensor/wink.py#L32-L33).

**Comment by xrolfex** [comment]
It kind of does to me, but I was following the lock pr that was just added. It is not similar to a switch in that it is still a binary setting? I have no problem trying it out under a switch. Let me test that out real quick.

**Comment by xrolfex** [comment]
It does not seem to send the correct request as a switch since the garage door property is position.

**Comment by balloob** [comment]
Okay, that makes sense. Then how is it different from a rollershutter? It has up, down and position property.

**Comment by xrolfex** [comment]
The roller shutter has position but that position is from 0 to 100 and has the ability to stop midway. The garage door through myq api's that wink uses is a position from 0 to 1 and does not have the ability to stop midway through.

**Pull request merged**
